#! /usr/bin/env sh

if test "$1" = "test"; then
   DEBUG_PARAM="-Dhuman=true"
fi

java ${DEBUG_PARAM} -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -Dfile.encoding=UTF-8 -jar `dirname $0`/tools/sbt-launch.jar "$@"
